import { EventEmitter } from 'events';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import logger from './logger.js';

// ──────────────────────────────────────────────
// TranscriptWatcher
// ──────────────────────────────────────────────
//
// Watches Claude Code transcript files in `~/.claude/projects/<encoded-cwd>/`
// for `{"type":"summary","summary":"..."}` lines and emits the latest summary
// per daemon session. Used to upgrade tab labels from the basename of cwd to
// a meaningful title generated by Claude Code.
//
// File-selection heuristic: for a given (cwd, startedAt) we poll the project
// directory and lock onto the .jsonl whose mtime is closest to `startedAt`
// among files not already claimed by another watched session. This handles
// the common case (one Claude per cwd) cleanly and degrades gracefully for
// multiple concurrent sessions in the same cwd — the wrong file may be
// claimed initially but `findCandidateFile` runs only until we lock on, and
// the deriveName numeric suffix still keeps tabs distinguishable.
//
// Partial-line safety: file is read incrementally by byte offset. We buffer
// any tail bytes past the final `\n` and prepend on the next poll so JSON
// lines split across reads parse correctly.

export interface TranscriptWatcherOptions {
  /** Override the base directory (defaults to `~/.claude/projects`). */
  baseDir?: string;
  /** Poll interval ms (default 2000). */
  pollIntervalMs?: number;
  /** Files modified earlier than `startedAt - mtimeSlackMs` are ignored. */
  mtimeSlackMs?: number;
}

interface WatchState {
  cwd: string;
  startedAt: number;
  file: string | null;
  offset: number;
  carry: string;
}

export class TranscriptWatcher extends EventEmitter {
  private states = new Map<string, WatchState>();
  private filesInUse = new Set<string>();
  private timer: ReturnType<typeof setInterval> | null = null;
  private readonly baseDir: string;
  private readonly pollIntervalMs: number;
  private readonly mtimeSlackMs: number;

  constructor(opts: TranscriptWatcherOptions = {}) {
    super();
    this.baseDir = opts.baseDir ?? path.join(os.homedir(), '.claude', 'projects');
    this.pollIntervalMs = opts.pollIntervalMs ?? 2000;
    this.mtimeSlackMs = opts.mtimeSlackMs ?? 5000;
  }

  watch(sessionId: string, cwd: string, startedAt: number): void {
    if (this.states.has(sessionId)) return;
    this.states.set(sessionId, {
      cwd,
      startedAt,
      file: null,
      offset: 0,
      carry: '',
    });
    if (!this.timer) {
      this.timer = setInterval(() => {
        void this.pollAll();
      }, this.pollIntervalMs);
      this.timer.unref();
    }
    // Eagerly poll so newly-created sessions don't wait a full interval.
    void this.pollOne(sessionId);
  }

  unwatch(sessionId: string): void {
    const s = this.states.get(sessionId);
    if (!s) return;
    if (s.file) this.filesInUse.delete(s.file);
    this.states.delete(sessionId);
    if (this.states.size === 0 && this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }

  stopAll(): void {
    for (const id of Array.from(this.states.keys())) this.unwatch(id);
  }

  // ────────────────────────────────────────────

  private async pollAll(): Promise<void> {
    for (const id of Array.from(this.states.keys())) {
      await this.pollOne(id);
    }
  }

  private async pollOne(sessionId: string): Promise<void> {
    const state = this.states.get(sessionId);
    if (!state) return;
    try {
      if (!state.file) {
        const file = await this.findCandidateFile(state.cwd, state.startedAt);
        if (!file) return;
        state.file = file;
        this.filesInUse.add(file);
      }
      const stat = await fs.promises.stat(state.file).catch(() => null);
      if (!stat || stat.size <= state.offset) return;
      const length = stat.size - state.offset;
      const buf = Buffer.alloc(length);
      const fh = await fs.promises.open(state.file, 'r');
      try {
        await fh.read(buf, 0, length, state.offset);
      } finally {
        await fh.close();
      }
      state.offset = stat.size;
      const combined = state.carry + buf.toString('utf8');
      const nlIdx = combined.lastIndexOf('\n');
      const consumed = nlIdx >= 0 ? combined.slice(0, nlIdx) : '';
      state.carry = nlIdx >= 0 ? combined.slice(nlIdx + 1) : combined;
      if (!consumed) return;
      let latest: string | null = null;
      for (const line of consumed.split('\n')) {
        if (!line) continue;
        try {
          const obj = JSON.parse(line) as { type?: string; summary?: unknown };
          if (obj.type === 'summary' && typeof obj.summary === 'string') {
            latest = obj.summary;
          }
        } catch {
          // partial or non-JSON line — skip
        }
      }
      if (latest) this.emit('summary', sessionId, latest);
    } catch (err) {
      logger.debug(`TranscriptWatcher pollOne(${sessionId}) failed: ${String(err)}`);
    }
  }

  private async findCandidateFile(
    cwd: string,
    startedAt: number
  ): Promise<string | undefined> {
    const dir = path.join(this.baseDir, encodeCwd(cwd));
    let entries: string[];
    try {
      entries = await fs.promises.readdir(dir);
    } catch {
      return undefined;
    }
    let best: { file: string; distance: number } | undefined;
    for (const entry of entries) {
      if (!entry.endsWith('.jsonl')) continue;
      const full = path.join(dir, entry);
      if (this.filesInUse.has(full)) continue;
      const stat = await fs.promises.stat(full).catch(() => null);
      if (!stat) continue;
      if (stat.mtimeMs < startedAt - this.mtimeSlackMs) continue;
      const distance = Math.abs(stat.mtimeMs - startedAt);
      if (!best || distance < best.distance) {
        best = { file: full, distance };
      }
    }
    return best?.file;
  }
}

/**
 * Claude Code encodes a cwd into its project-dir name by replacing every `/`
 * and `.` with `-`. (e.g. `/home/u/.claude` → `-home-u--claude`.)
 */
export function encodeCwd(cwd: string): string {
  return cwd.replace(/[/.]/g, '-');
}
